version: "3.8"

services:
  server:
    # image: "nginx:stable-alpine"
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - "8000:80"
    # volumes:
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysqldb
      - artisan
      - npm
  php:
    build: 
      context: .
      dockerfile: docker/php.dockerfile
    # volumes:
    #   - ./src:/var/www/html:delegated
  mysqldb:
    image: mysql:8.0
    environment:
      - ./env/mysql.env
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_RANDOM_ROOT_PASSWORD=no
  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:18-alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html